import { TripPlan } from "./types";

export const sampleTrip: TripPlan = {
  city: "Lisbon",
  month: "May",
  weather_note: "May in Lisbon: 22°C, sunny, occasional Atlantic breeze. Perfect walking weather.",
  total_cost_estimate_usd: 287,
  cost_per_day_usd: 96,
  budget_status: "within",
  days: [
    {
      day_number: 1,
      theme: "ALFAMA + WATERFRONT GOLDEN HOUR",
      morning: [
        {
          name: "Manteigaria",
          description: "Watch them torch pastéis de nata through the window. Eat two standing up. This is the one locals actually go to.",
          price_tier: "$",
          estimated_cost_usd_pp: 4,
          time_at_spot_minutes: 20,
          travel_to_next: { minutes: 8, mode: "walk" },
          trending_badge: "Trending on TikTok",
          trending_source_note: "Over 12M views on TikTok for the window torch process. Multiple 2024-2025 viral videos.",
          lat: 38.7104,
          lng: -9.1422,
          google_maps_url: "https://maps.google.com/?q=Manteigaria+Lisbon",
          official_url: null,
          booking_url: null,
        },
        {
          name: "Feira da Ladra",
          description: "Tuesday and Saturday flea market. Tiles, records, military badges, someone's grandmother's entire china set. Arrive before 11 or the good stuff walks.",
          price_tier: "$",
          estimated_cost_usd_pp: 0,
          time_at_spot_minutes: 60,
          travel_to_next: { minutes: 5, mode: "walk" },
          trending_badge: "Reddit local pick",
          trending_source_note: "Consistently recommended in r/Lisbon and r/travel as the best flea market in southern Europe.",
          lat: 38.7148,
          lng: -9.1245,
          google_maps_url: "https://maps.google.com/?q=Feira+da+Ladra+Lisbon",
          official_url: null,
          booking_url: null,
        },
      ],
      afternoon: [
        {
          name: "Alfama self-guided walk",
          description: "Get lost on purpose. The GPS will fail you in the best way. Every dead end has a viewpoint or a cat.",
          price_tier: "$",
          estimated_cost_usd_pp: 0,
          time_at_spot_minutes: 90,
          travel_to_next: { minutes: 3, mode: "walk" },
          trending_badge: "Classic must-see",
          trending_source_note: "Every major Lisbon guide from Lonely Planet to local blogs lists Alfama as essential. Still earns it.",
          lat: 38.7117,
          lng: -9.1301,
          google_maps_url: "https://maps.google.com/?q=Alfama+Lisbon",
          official_url: null,
          booking_url: null,
        },
        {
          name: "Taberna da Rua das Flores",
          description: "Tiny room, no menu, they tell you what's good today. Usually involves octopus. Trust them.",
          price_tier: "$$",
          estimated_cost_usd_pp: 28,
          time_at_spot_minutes: 75,
          travel_to_next: { minutes: 12, mode: "walk" },
          trending_badge: "Local blog favorite",
          trending_source_note: "Featured in Eater Lisbon, multiple Portuguese food blogs. No reservations — show up at 12:30 or wait.",
          lat: 38.7118,
          lng: -9.1453,
          google_maps_url: "https://maps.google.com/?q=Taberna+da+Rua+das+Flores+Lisbon",
          official_url: null,
          booking_url: null,
        },
      ],
      evening: [
        {
          name: "Miradouro da Graça",
          description: "The sunset viewpoint that isn't overrun. Grab a Sagres from the kiosk, sit on the wall, watch the city turn gold.",
          price_tier: "$",
          estimated_cost_usd_pp: 3,
          time_at_spot_minutes: 45,
          travel_to_next: { minutes: 15, mode: "walk" },
          trending_badge: "Hidden gem",
          trending_source_note: "Reddit r/Lisbon frequently recommends Graça over the more famous Santa Luzia for sunset.",
          lat: 38.7178,
          lng: -9.1312,
          google_maps_url: "https://maps.google.com/?q=Miradouro+da+Graça+Lisbon",
          official_url: null,
          booking_url: null,
        },
        {
          name: "Cervejaria Ramiro",
          description: "Seafood institution. The tiger prawns are the size of your hand. End with a steak sandwich — trust the tradition.",
          price_tier: "$$$",
          estimated_cost_usd_pp: 45,
          time_at_spot_minutes: 90,
          travel_to_next: null,
          trending_badge: "Classic must-see",
          trending_source_note: "Anthony Bourdain episode. Still packed nightly. Recent TripAdvisor reviews confirm quality unchanged.",
          lat: 38.7208,
          lng: -9.1358,
          google_maps_url: "https://maps.google.com/?q=Cervejaria+Ramiro+Lisbon",
          official_url: "https://www.cervejariaramiro.pt",
          booking_url: null,
        },
      ],
      day_total_usd: 80,
    },
    {
      day_number: 2,
      theme: "BELÉM + TIME TRAVEL + RIVERSIDE",
      morning: [
        {
          name: "Pastéis de Belém",
          description: "The original since 1837. Yes, the line is long. Yes, it moves fast. Yes, it's worth it. Sit in the back room.",
          price_tier: "$",
          estimated_cost_usd_pp: 5,
          time_at_spot_minutes: 30,
          travel_to_next: { minutes: 5, mode: "walk" },
          trending_badge: "Classic must-see",
          trending_source_note: "Universally cited as Lisbon's #1 food experience. 4.5 stars across 80K+ Google reviews.",
          lat: 38.6976,
          lng: -9.2033,
          google_maps_url: "https://maps.google.com/?q=Pastéis+de+Belém+Lisbon",
          official_url: "https://pasteisdebelem.pt",
          booking_url: null,
        },
        {
          name: "MAAT",
          description: "The building alone justifies the visit — a wave of white tiles on the waterfront. The exhibitions inside are hit or miss, the rooftop walk is always a hit.",
          price_tier: "$",
          estimated_cost_usd_pp: 10,
          time_at_spot_minutes: 60,
          travel_to_next: { minutes: 10, mode: "walk" },
          trending_badge: "Trending on TikTok",
          trending_source_note: "Rooftop walk is one of Lisbon's most Instagrammed spots. Architecture TikToks regularly hit 1M+ views.",
          lat: 38.6963,
          lng: -9.1952,
          google_maps_url: "https://maps.google.com/?q=MAAT+Lisbon",
          official_url: "https://www.maat.pt",
          booking_url: null,
        },
      ],
      afternoon: [
        {
          name: "Jerónimos Monastery",
          description: "16th-century Manueline architecture that makes your jaw actually drop. The cloister is the main event — every column tells a different story.",
          price_tier: "$",
          estimated_cost_usd_pp: 12,
          time_at_spot_minutes: 75,
          travel_to_next: { minutes: 8, mode: "walk" },
          trending_badge: "Classic must-see",
          trending_source_note: "UNESCO World Heritage Site. Consistently top 3 in every Lisbon itinerary published since forever.",
          lat: 38.6979,
          lng: -9.2068,
          google_maps_url: "https://maps.google.com/?q=Jerónimos+Monastery+Lisbon",
          official_url: null,
          booking_url: null,
        },
        {
          name: "LX Factory",
          description: "Industrial complex turned creative village. Bookshop inside a warehouse, craft beer on loading docks, street art on every surface that holds still.",
          price_tier: "$$",
          estimated_cost_usd_pp: 20,
          time_at_spot_minutes: 90,
          travel_to_next: { minutes: 20, mode: "bus" },
          trending_badge: "Trending on TikTok",
          trending_source_note: "Ler Devagar bookshop alone has millions of TikTok views. The whole complex trends regularly.",
          lat: 38.7037,
          lng: -9.1781,
          google_maps_url: "https://maps.google.com/?q=LX+Factory+Lisbon",
          official_url: "https://lxfactory.com",
          booking_url: null,
        },
      ],
      evening: [
        {
          name: "Time Out Market",
          description: "Food hall done right. 40 stalls curated by the magazine. Get the ceviche from Marlene Vieira, the steak from Café de São Bento, and a ginjinha to close.",
          price_tier: "$$",
          estimated_cost_usd_pp: 30,
          time_at_spot_minutes: 75,
          travel_to_next: { minutes: 5, mode: "walk" },
          trending_badge: "Reddit local pick",
          trending_source_note: "Reddit consensus: tourist trap but actually good. The key is knowing which stalls to hit.",
          lat: 38.7068,
          lng: -9.1459,
          google_maps_url: "https://maps.google.com/?q=Time+Out+Market+Lisbon",
          official_url: "https://www.timeoutmarket.com/lisboa",
          booking_url: null,
        },
        {
          name: "Pink Street (Rua Nova do Carvalho)",
          description: "Literally a pink street. Bar-hop territory. Start at Pensão Amor (burlesque bar in a former brothel) and let the night decide the rest.",
          price_tier: "$$",
          estimated_cost_usd_pp: 18,
          time_at_spot_minutes: 90,
          travel_to_next: null,
          trending_badge: "Trending on TikTok",
          trending_source_note: "The pink street photo is basically mandatory on Instagram. Pensão Amor interior videos go viral regularly.",
          lat: 38.7072,
          lng: -9.1451,
          google_maps_url: "https://maps.google.com/?q=Pink+Street+Lisbon",
          official_url: null,
          booking_url: null,
        },
      ],
      day_total_usd: 95,
    },
    {
      day_number: 3,
      theme: "SINTRA DAY TRIP + FAREWELL DINNER",
      morning: [
        {
          name: "Train to Sintra",
          description: "40 minutes from Rossio station. €2.30 each way. The train itself passes through increasingly fairy-tale scenery.",
          price_tier: "$",
          estimated_cost_usd_pp: 5,
          time_at_spot_minutes: 40,
          travel_to_next: { minutes: 15, mode: "walk" },
          trending_badge: "Classic must-see",
          trending_source_note: "Every Lisbon 3-day itinerary includes Sintra. The train is the smart move — driving and parking is chaos.",
          lat: 38.7982,
          lng: -9.3811,
          google_maps_url: "https://maps.google.com/?q=Sintra+Train+Station",
          official_url: null,
          booking_url: null,
        },
        {
          name: "Pena Palace",
          description: "A Romanticist fever dream on a hilltop. Red, yellow, blue — it looks AI-generated but it's from 1854. The terraces have views to the Atlantic.",
          price_tier: "$$",
          estimated_cost_usd_pp: 16,
          time_at_spot_minutes: 120,
          travel_to_next: { minutes: 25, mode: "walk" },
          trending_badge: "Trending on TikTok",
          trending_source_note: "One of the most-filmed palaces in Europe on TikTok. Drone shots regularly break 5M views.",
          lat: 38.7876,
          lng: -9.3907,
          google_maps_url: "https://maps.google.com/?q=Pena+Palace+Sintra",
          official_url: "https://www.parquesdesintra.pt",
          booking_url: "https://www.parquesdesintra.pt/en/parks-and-monuments/park-and-national-palace-of-pena/",
        },
      ],
      afternoon: [
        {
          name: "Quinta da Regaleira",
          description: "Underground initiation wells, secret tunnels, gothic chapel. The well spiral staircase is one of those once-in-a-lifetime photo moments.",
          price_tier: "$$",
          estimated_cost_usd_pp: 12,
          time_at_spot_minutes: 90,
          travel_to_next: { minutes: 10, mode: "walk" },
          trending_badge: "Trending on TikTok",
          trending_source_note: "The initiation well is one of Portugal's most viral locations. Over 50M combined TikTok views.",
          lat: 38.7965,
          lng: -9.3959,
          google_maps_url: "https://maps.google.com/?q=Quinta+da+Regaleira+Sintra",
          official_url: "https://www.rfregaleira.pt",
          booking_url: "https://www.rfregaleira.pt/en/tickets",
        },
        {
          name: "Tascantiga (Sintra)",
          description: "Tiny wine bar on the main drag. Local cheeses, presunto, and wines by the glass. The owner will talk your ear off about Colares wines — let him.",
          price_tier: "$$",
          estimated_cost_usd_pp: 18,
          time_at_spot_minutes: 45,
          travel_to_next: { minutes: 40, mode: "metro" },
          trending_badge: "Local blog favorite",
          trending_source_note: "Featured in multiple Portuguese food blogs as Sintra's best casual wine spot.",
          lat: 38.7972,
          lng: -9.3903,
          google_maps_url: "https://maps.google.com/?q=Tascantiga+Sintra",
          official_url: null,
          booking_url: null,
        },
      ],
      evening: [
        {
          name: "Belcanto",
          description: "José Avillez's two-star Michelin flagship. The 'Garden of the Goose' dessert is theater. Splurge meal — this is how you end a Lisbon trip.",
          price_tier: "$$$$",
          estimated_cost_usd_pp: 60,
          time_at_spot_minutes: 120,
          travel_to_next: null,
          trending_badge: "Classic must-see",
          trending_source_note: "Two Michelin stars. Regularly on World's 50 Best extended list. 2024 reviews confirm it's still at peak.",
          lat: 38.7105,
          lng: -9.1406,
          google_maps_url: "https://maps.google.com/?q=Belcanto+Lisbon",
          official_url: "https://www.belcanto.pt",
          booking_url: "https://www.belcanto.pt/en/reservations",
        },
      ],
      day_total_usd: 112,
    },
  ],
  themed_lists: {
    best_food: [
      {
        name: "Cervejaria Ramiro",
        description: "Seafood institution. Tiger prawns the size of your hand.",
        price_tier: "$$$",
        estimated_cost_usd_pp: 45,
        time_at_spot_minutes: 90,
        travel_to_next: null,
        trending_badge: "Classic must-see",
        trending_source_note: "Bourdain-approved. Still delivers.",
        lat: 38.7208,
        lng: -9.1358,
        google_maps_url: "https://maps.google.com/?q=Cervejaria+Ramiro+Lisbon",
        official_url: "https://www.cervejariaramiro.pt",
        booking_url: null,
      },
      {
        name: "Manteigaria",
        description: "The nata place locals actually go to.",
        price_tier: "$",
        estimated_cost_usd_pp: 4,
        time_at_spot_minutes: 20,
        travel_to_next: null,
        trending_badge: "Trending on TikTok",
        trending_source_note: "12M+ TikTok views on the torch process.",
        lat: 38.7104,
        lng: -9.1422,
        google_maps_url: "https://maps.google.com/?q=Manteigaria+Lisbon",
        official_url: null,
        booking_url: null,
      },
      {
        name: "O Velho Eurico",
        description: "Hole in the wall in Alfama. Grilled sardines on bread. That's it. That's the whole menu.",
        price_tier: "$",
        estimated_cost_usd_pp: 12,
        time_at_spot_minutes: 45,
        travel_to_next: null,
        trending_badge: "Hidden gem",
        trending_source_note: "Local food bloggers call this the most authentic sardine experience in Alfama.",
        lat: 38.7121,
        lng: -9.1298,
        google_maps_url: "https://maps.google.com/?q=O+Velho+Eurico+Lisbon",
        official_url: null,
        booking_url: null,
      },
      {
        name: "Café Janis",
        description: "Brunch that doesn't feel like a brunch place. Great natural wines, better people-watching.",
        price_tier: "$$",
        estimated_cost_usd_pp: 18,
        time_at_spot_minutes: 60,
        travel_to_next: null,
        trending_badge: "Reddit local pick",
        trending_source_note: "r/Lisbon regulars recommend for Saturday brunch.",
        lat: 38.7135,
        lng: -9.1468,
        google_maps_url: "https://maps.google.com/?q=Café+Janis+Lisbon",
        official_url: null,
        booking_url: null,
      },
      {
        name: "Ponto Final",
        description: "Cross the river to Cacilhas for the best grilled fish view in Lisbon. Literally on the water.",
        price_tier: "$$",
        estimated_cost_usd_pp: 22,
        time_at_spot_minutes: 75,
        travel_to_next: null,
        trending_badge: "Local blog favorite",
        trending_source_note: "Every Lisbon food blog mentions the ferry ride + fish combo.",
        lat: 38.6874,
        lng: -9.1488,
        google_maps_url: "https://maps.google.com/?q=Ponto+Final+Cacilhas",
        official_url: null,
        booking_url: null,
      },
    ],
    best_views: [
      {
        name: "Miradouro da Graça",
        description: "The sunset viewpoint that isn't overrun.",
        price_tier: "$",
        estimated_cost_usd_pp: 3,
        time_at_spot_minutes: 30,
        travel_to_next: null,
        trending_badge: "Hidden gem",
        trending_source_note: "Reddit locals prefer this over Santa Luzia.",
        lat: 38.7178,
        lng: -9.1312,
        google_maps_url: "https://maps.google.com/?q=Miradouro+da+Graça+Lisbon",
        official_url: null,
        booking_url: null,
      },
      {
        name: "Miradouro da Senhora do Monte",
        description: "Highest viewpoint in Lisbon. The whole city, the river, the bridge. Quiet at sunrise.",
        price_tier: "$",
        estimated_cost_usd_pp: 0,
        time_at_spot_minutes: 20,
        travel_to_next: null,
        trending_badge: "Hidden gem",
        trending_source_note: "Known locally as the photographer's viewpoint. Less crowded than Portas do Sol.",
        lat: 38.7192,
        lng: -9.1338,
        google_maps_url: "https://maps.google.com/?q=Miradouro+Senhora+do+Monte+Lisbon",
        official_url: null,
        booking_url: null,
      },
      {
        name: "MAAT Rooftop Walk",
        description: "Walk on top of the museum. The curve of the building frames the river.",
        price_tier: "$",
        estimated_cost_usd_pp: 0,
        time_at_spot_minutes: 20,
        travel_to_next: null,
        trending_badge: "Trending on TikTok",
        trending_source_note: "Architecture TikTok staple.",
        lat: 38.6963,
        lng: -9.1952,
        google_maps_url: "https://maps.google.com/?q=MAAT+Lisbon",
        official_url: "https://www.maat.pt",
        booking_url: null,
      },
      {
        name: "Elevador de Santa Justa",
        description: "Gothic iron elevator from 1902. Skip the line by entering from the top via Carmo.",
        price_tier: "$",
        estimated_cost_usd_pp: 6,
        time_at_spot_minutes: 15,
        travel_to_next: null,
        trending_badge: "Classic must-see",
        trending_source_note: "The Carmo shortcut is a well-known local hack shared on Reddit.",
        lat: 38.7121,
        lng: -9.1393,
        google_maps_url: "https://maps.google.com/?q=Elevador+Santa+Justa+Lisbon",
        official_url: null,
        booking_url: null,
      },
      {
        name: "Cristo Rei",
        description: "Lisbon's Christ the Redeemer. Take the ferry — the approach is the view.",
        price_tier: "$",
        estimated_cost_usd_pp: 8,
        time_at_spot_minutes: 45,
        travel_to_next: null,
        trending_badge: "Classic must-see",
        trending_source_note: "Ferry + statue combo is a classic Lisbon half-day trip.",
        lat: 38.6786,
        lng: -9.1714,
        google_maps_url: "https://maps.google.com/?q=Cristo+Rei+Lisbon",
        official_url: null,
        booking_url: null,
      },
    ],
    best_nightlife: [
      {
        name: "Pensão Amor",
        description: "Burlesque bar in a former brothel. The decor tells the story.",
        price_tier: "$$",
        estimated_cost_usd_pp: 15,
        time_at_spot_minutes: 60,
        travel_to_next: null,
        trending_badge: "Trending on TikTok",
        trending_source_note: "Interior design videos go viral regularly.",
        lat: 38.7072,
        lng: -9.1451,
        google_maps_url: "https://maps.google.com/?q=Pensão+Amor+Lisbon",
        official_url: null,
        booking_url: null,
      },
      {
        name: "Lux Frágil",
        description: "John Malkovich co-owned this. Still the best electronic music venue in Lisbon.",
        price_tier: "$$",
        estimated_cost_usd_pp: 20,
        time_at_spot_minutes: 180,
        travel_to_next: null,
        trending_badge: "Classic must-see",
        trending_source_note: "Resident Advisor consistently ranks it among Europe's best clubs.",
        lat: 38.7138,
        lng: -9.1183,
        google_maps_url: "https://maps.google.com/?q=Lux+Frágil+Lisbon",
        official_url: null,
        booking_url: null,
      },
      {
        name: "Topo Chiado",
        description: "Rooftop bar with castle views. Great gin tonics, better sunset.",
        price_tier: "$$",
        estimated_cost_usd_pp: 14,
        time_at_spot_minutes: 60,
        travel_to_next: null,
        trending_badge: "Reddit local pick",
        trending_source_note: "r/Lisbon's most recommended rooftop bar.",
        lat: 38.7118,
        lng: -9.1410,
        google_maps_url: "https://maps.google.com/?q=Topo+Chiado+Lisbon",
        official_url: null,
        booking_url: null,
      },
      {
        name: "A Ginjinha",
        description: "One drink, one shot glass, one euro. The original ginjinha bar since 1840.",
        price_tier: "$",
        estimated_cost_usd_pp: 2,
        time_at_spot_minutes: 10,
        travel_to_next: null,
        trending_badge: "Classic must-see",
        trending_source_note: "The most-photographed shot glass in Lisbon.",
        lat: 38.7142,
        lng: -9.1393,
        google_maps_url: "https://maps.google.com/?q=A+Ginjinha+Lisbon",
        official_url: null,
        booking_url: null,
      },
      {
        name: "Bar Tejo",
        description: "Wine bar on a tiny Alfama street. Four tables, a hundred bottles, zero pretense.",
        price_tier: "$$",
        estimated_cost_usd_pp: 12,
        time_at_spot_minutes: 60,
        travel_to_next: null,
        trending_badge: "Hidden gem",
        trending_source_note: "Local wine bloggers consider this Alfama's best-kept secret.",
        lat: 38.7112,
        lng: -9.1305,
        google_maps_url: "https://maps.google.com/?q=Bar+Tejo+Lisbon",
        official_url: null,
        booking_url: null,
      },
    ],
    best_hidden_gems: [
      {
        name: "Jardim Botânico de Lisboa",
        description: "Victorian greenhouse hiding in plain sight. Orchids, cacti, and total silence in the middle of the city.",
        price_tier: "$",
        estimated_cost_usd_pp: 4,
        time_at_spot_minutes: 45,
        travel_to_next: null,
        trending_badge: "Hidden gem",
        trending_source_note: "Rarely appears in tourist guides. Local bloggers keep it for themselves.",
        lat: 38.7166,
        lng: -9.1485,
        google_maps_url: "https://maps.google.com/?q=Jardim+Botânico+Lisboa",
        official_url: null,
        booking_url: null,
      },
      {
        name: "Village Underground Lisboa",
        description: "Shipping containers and double-decker buses turned into creative studios. Free concerts on weekends.",
        price_tier: "$",
        estimated_cost_usd_pp: 0,
        time_at_spot_minutes: 30,
        travel_to_next: null,
        trending_badge: "Hidden gem",
        trending_source_note: "Known in the creative scene but almost never in tourist itineraries.",
        lat: 38.7051,
        lng: -9.1774,
        google_maps_url: "https://maps.google.com/?q=Village+Underground+Lisboa",
        official_url: null,
        booking_url: null,
      },
      {
        name: "Panteão Nacional (terrace)",
        description: "Everyone visits the monument. Almost nobody goes to the rooftop terrace. 360° view, nobody there.",
        price_tier: "$",
        estimated_cost_usd_pp: 5,
        time_at_spot_minutes: 30,
        travel_to_next: null,
        trending_badge: "Hidden gem",
        trending_source_note: "Reddit comments consistently call the terrace Lisbon's most underrated viewpoint.",
        lat: 38.7149,
        lng: -9.1245,
        google_maps_url: "https://maps.google.com/?q=Panteão+Nacional+Lisbon",
        official_url: null,
        booking_url: null,
      },
      {
        name: "Casa do Alentejo",
        description: "Walk through a nondescript door into a Moorish palace courtyard. Restaurant upstairs serves Alentejo food at local prices.",
        price_tier: "$",
        estimated_cost_usd_pp: 15,
        time_at_spot_minutes: 60,
        travel_to_next: null,
        trending_badge: "Hidden gem",
        trending_source_note: "The courtyard reveal is a famous Lisbon 'secret' shared in local blogs and Reddit threads.",
        lat: 38.7157,
        lng: -9.1405,
        google_maps_url: "https://maps.google.com/?q=Casa+do+Alentejo+Lisbon",
        official_url: null,
        booking_url: null,
      },
      {
        name: "Livraria Bertrand (Chiado)",
        description: "World's oldest bookshop (1732). Still operating. The back rooms feel like a time machine.",
        price_tier: "$",
        estimated_cost_usd_pp: 0,
        time_at_spot_minutes: 20,
        travel_to_next: null,
        trending_badge: "Hidden gem",
        trending_source_note: "Holds the Guinness World Record. Still somehow overlooked by most tourists rushing to LX Factory.",
        lat: 38.7109,
        lng: -9.1418,
        google_maps_url: "https://maps.google.com/?q=Livraria+Bertrand+Chiado+Lisbon",
        official_url: null,
        booking_url: null,
      },
    ],
  },
};
